from os import getenv

DATABASE_HOST = getenv('DATABASE_HOST', '')
DATABASE_PORT = getenv('DATABASE_PORT', '')
DATABASE_NAME = getenv('DATABASE_NAME', '')
DATABASE_USER = getenv('DATABASE_USER', '')
DATABASE_PASSWORD = getenv('DATABASE_PASSWORD', '')

TEST_DATABASE_HOST = getenv('TEST_DATABASE_HOST', '')
TEST_DATABASE_PORT = getenv('TEST_DATABASE_PORT', '')
TEST_DATABASE_NAME = getenv('TEST_DATABASE_NAME', '')
TEST_DATABASE_USER = getenv('TEST_DATABASE_USER', '')
TEST_DATABASE_PASSWORD = getenv('TEST_DATABASE_PASSWORD', '')
