from app.constants import (
    TEST_DATABASE_USER,
    TEST_DATABASE_PASSWORD,
    TEST_DATABASE_NAME,
    TEST_DATABASE_HOST,
    TEST_DATABASE_PORT
)
from .default import *

TESTING = True
DEBUG = True

APP_ENV = APP_ENV_TESTING

WTF_CSRF_ENABLED = False

SQLALCHEMY_DATABASE_URI = (
    f'mysql+pymysql://'
    f'{TEST_DATABASE_USER}:{TEST_DATABASE_PASSWORD}@'
    f'{TEST_DATABASE_HOST}:{TEST_DATABASE_PORT}/{TEST_DATABASE_NAME}'
)
